services:
    db:
        image: mysql:latest
        container_name: expenditure-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: m1nam00813
            MYSQL_DATABASE: ExpenditureBook
            TZ: "Asia/Tokyo"
        volumes:
            - ./my.cnf:/etc/mysql/conf.d/my.cnf

